services:
  laravel-app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: fintrack-ledger-image:v1.0.0 
    container_name: fintrack-ledger-container
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - fintrack-ledger-network
    depends_on: 
      db:
        condition: service_healthy  # Wait for the MySQL container to be healthy
    environment:
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: fintrack-ledger-db-container
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

  db:
    image: mysql:8.0
    container_name: fintrack-ledger-db-container
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - fintrack-ledger-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:alpine
    container_name: fintrack-ledger-nginx-container
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - fintrack-ledger-network

networks:
  fintrack-ledger-network:
    driver: bridge

volumes:
  db-data: